/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PriceLoader.java
 *
 * Created on 20.04.2011, 14:21:00
 */
package xframes;

import java.awt.Color;
import java.io.File;
import java.util.Calendar;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdesktop.application.Action;
import org.jdesktop.application.Task;
import priceloader.vm2.AbstractPriceLoaderVM2;
import priceloader.vm2.DimohodPriceLoader;
import priceloader.vm2.MerlionPriceLoader;
import priceloader.vm2.OscariaPriceLoader;
import priceloader.vm2.StackMisgrPriceLoader;
import priceloader.vm2.StackRadiopokupkaPriceLoader;
import priceloader.vm2.StackRambahPriceLoader;
import priceloader.vm2.StandartPriceLoader;
import priceloader.vm2.TBVisavisPriceLoader;
import tools.Messages;
import vmre.GlobalHacks;
import vmre.VMREApp;
import vmre.utils.BackupHSQLDB;
import vmre.utils.GlobalClasses;

/**
 *
 * @author grigory
 */
public class PriceLoader extends javax.swing.JPanel {

    public static String title = "Загрузчик стандартного прайс-листа";

    /** Creates new form PriceLoader */
    public PriceLoader() {
        initComponents();
        progress.setStringPainted(true);
        progress.setForeground(Color.ORANGE);
        progress.setBackground(Color.DARK_GRAY);

        //performGlobalHacks();
    }

    public void performGlobalHacks() {
        Messages.show("Выполняем глобальные хаки");
        if (GlobalHacks.is_dimohod == 1) {
            lbLoadPrice1.setText("Прайс-Лист Дымоходы :");
        }
        if (GlobalHacks.is_rambah == 1) {
            lbLoadPrice1.setText("Прайс-Лист Rambach :");
        }
        if (GlobalHacks.is_misgrru == 1) {
            lbLoadPrice1.setText("Прайс-Лист Misgrru :");
        }
        if (GlobalHacks.is_merlionru == 1) {
            lbLoadPrice1.setText("Прайс-Лист Merlion :");
        }
        if (GlobalHacks.is_radiopokupka == 1) {
            lbLoadPrice1.setText("Прайс-Лист Radiopokupka :");
        }
        if (GlobalHacks.is_oscaria == 1) {
            lbLoadPrice1.setText("Прайс-Лист Oscaria :");
        }
        if (GlobalHacks.is_tulabel == 1) {
            lbLoadPrice1.setText("Прайс-Лист Visavi:");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelPrices = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();
        lbProgress = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbLoadPrice1 = new javax.swing.JLabel();
        btLoadPrice1 = new javax.swing.JButton();
        txCurs1 = new javax.swing.JTextField();
        txLoadPrice1 = new javax.swing.JTextField();
        startLine = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        xsheet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ttData = new javax.swing.JLabel();
        ttData1 = new javax.swing.JLabel();
        ttData2 = new javax.swing.JLabel();
        endLine = new javax.swing.JTextField();
        ttData3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endSheet = new javax.swing.JTextField();
        ttData4 = new javax.swing.JLabel();
        ttData5 = new javax.swing.JLabel();
        ttData6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taReport = new javax.swing.JTextArea();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(vmre.VMREApp.class).getContext().getResourceMap(PriceLoader.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        btCancelPrices.setIcon(resourceMap.getIcon("btCancelPrices.icon")); // NOI18N
        btCancelPrices.setText(resourceMap.getString("btCancelPrices.text")); // NOI18N
        btCancelPrices.setName("btCancelPrices"); // NOI18N
        btCancelPrices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelPricesActionPerformed(evt);
            }
        });

        progress.setName("progress"); // NOI18N

        lbProgress.setText(resourceMap.getString("lbProgress.text")); // NOI18N
        lbProgress.setName("lbProgress"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        lbLoadPrice1.setText(resourceMap.getString("lbLoadPrice1.text")); // NOI18N
        lbLoadPrice1.setName("lbLoadPrice1"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(vmre.VMREApp.class).getContext().getActionMap(PriceLoader.class, this);
        btLoadPrice1.setAction(actionMap.get("openPrice1")); // NOI18N
        btLoadPrice1.setIcon(resourceMap.getIcon("btLoadPrice1.icon")); // NOI18N
        btLoadPrice1.setText(resourceMap.getString("btLoadPrice1.text")); // NOI18N
        btLoadPrice1.setName("btLoadPrice1"); // NOI18N

        txCurs1.setText(resourceMap.getString("txCurs1.text")); // NOI18N
        txCurs1.setToolTipText(resourceMap.getString("txCurs1.toolTipText")); // NOI18N
        txCurs1.setName("txCurs1"); // NOI18N

        txLoadPrice1.setText(resourceMap.getString("txLoadPrice1.text")); // NOI18N
        txLoadPrice1.setName("txLoadPrice1"); // NOI18N

        startLine.setText(resourceMap.getString("startLine.text")); // NOI18N
        startLine.setName("startLine"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        xsheet.setText(resourceMap.getString("xsheet.text")); // NOI18N
        xsheet.setName("xsheet"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ttData.setToolTipText(resourceMap.getString("ttData.toolTipText")); // NOI18N
        ttData.setName("ttData"); // NOI18N

        ttData1.setToolTipText(resourceMap.getString("ttData1.toolTipText")); // NOI18N
        ttData1.setName("ttData1"); // NOI18N

        ttData2.setToolTipText(resourceMap.getString("ttData2.toolTipText")); // NOI18N
        ttData2.setName("ttData2"); // NOI18N

        endLine.setText(resourceMap.getString("endLine.text")); // NOI18N
        endLine.setName("endLine"); // NOI18N

        ttData3.setToolTipText(resourceMap.getString("ttData3.toolTipText")); // NOI18N
        ttData3.setName("ttData3"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        endSheet.setText(resourceMap.getString("endSheet.text")); // NOI18N
        endSheet.setName("endSheet"); // NOI18N

        ttData4.setIcon(null);
        ttData4.setToolTipText(resourceMap.getString("ttData4.toolTipText")); // NOI18N
        ttData4.setName("ttData4"); // NOI18N

        ttData5.setIcon(null);
        ttData5.setToolTipText(resourceMap.getString("ttData5.toolTipText")); // NOI18N
        ttData5.setName("ttData5"); // NOI18N

        ttData6.setIcon(null);
        ttData6.setToolTipText(resourceMap.getString("ttData6.toolTipText")); // NOI18N
        ttData6.setName("ttData6"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLoadPrice1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txLoadPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(xsheet, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addComponent(startLine)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btLoadPrice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txCurs1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(ttData))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ttData4))))
                    .addComponent(ttData3)
                    .addComponent(ttData2)
                    .addComponent(ttData1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(endLine)
                            .addComponent(endSheet, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttData6)
                            .addComponent(ttData5))))
                .addContainerGap(84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ttData5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ttData)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btLoadPrice1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbLoadPrice1)
                                    .addComponent(txLoadPrice1)))
                            .addComponent(ttData4)
                            .addComponent(txCurs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ttData1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(xsheet, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(endSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ttData2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startLine, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(endLine, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ttData6))
                .addGap(34, 34, 34)
                .addComponent(ttData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btLoadPrice1, startLine, txCurs1, txLoadPrice1});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {endSheet, xsheet});

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        taReport.setColumns(20);
        taReport.setFont(resourceMap.getFont("taReport.font")); // NOI18N
        taReport.setRows(5);
        taReport.setName("taReport"); // NOI18N
        jScrollPane1.setViewportView(taReport);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCancelPrices, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbProgress))
                        .addGap(296, 296, 296))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(190, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lbProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCancelPrices, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelPricesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelPricesActionPerformed
        actions.ActionsMainFrame.Tree().execute();
    }//GEN-LAST:event_btCancelPricesActionPerformed

    @Action
    public Task openPrice1() {
        return new org.jdesktop.application.Task(org.jdesktop.application.Application.getInstance(VMREApp.class)) {

            @Override
            protected Object doInBackground() {
                if(GlobalHacks.is_free==1){
                    JOptionPane.showMessageDialog(null, "Загрузка прайса недоступна в бесплатной версии.");
                    return null; 
                }
                Preferences prefs = GlobalClasses.getPrefs();
                String folder = prefs.get("prices_folder", "");
                if (folder.equalsIgnoreCase("")) {
                    folder = null;
                }
                JFileChooser fch = new JFileChooser(folder);
                File f = null;

                switch (fch.showOpenDialog(null)) {
                    case JFileChooser.APPROVE_OPTION:
                        f = fch.getSelectedFile();
                        prefs.put("prices_folder", f.getPath());
                        break;
                    default:
                        return null;
                }
                if (!testCurs(txCurs1)) {
                    return null;
                }

                if (!testStartLine(startLine)) {
                    return null;
                }
                BackupHSQLDB.backupDB();
                AbstractPriceLoaderVM2 pr;
                Messages.use_ta = true;
                taReport.setText("");
                Messages.ta = taReport;


                pr = new StandartPriceLoader();

                if (GlobalHacks.is_dimohod == 1) {
                    Messages.show("Dimohod  price loader");
                    pr = new DimohodPriceLoader();
                }
                if (GlobalHacks.is_rambah == 1) {
                    Messages.show("Прайс лист Rambah");
                    pr = new StackRambahPriceLoader();
                }
                if (GlobalHacks.is_misgrru == 1) {
                    Messages.show("Misgrru  price loader");
                    pr = new StackMisgrPriceLoader();
                }
                if (GlobalHacks.is_merlionru == 1) {
                    Messages.show("Misgrru  price loader");
                    pr = new MerlionPriceLoader();
                }

                if (GlobalHacks.is_radiopokupka == 1) {
                    Messages.show("Radiopokupka  price loader");
                    pr = new StackRadiopokupkaPriceLoader();
                }
                
                if (GlobalHacks.is_oscaria == 1) {
                    Messages.show("oscaria  price loader");
                    pr = new OscariaPriceLoader();
                }
                
                if (GlobalHacks.is_tulabel == 1) {
                    Messages.show("tulabel  price loader");
                    pr = new TBVisavisPriceLoader();
                }


                pr.copyFile(f.getAbsolutePath(), false);
                pr.curs = Double.parseDouble(txCurs1.getText());
                
                Integer xstartLine=Integer.parseInt(startLine.getText());
                Integer xendLine=Integer.parseInt(endLine.getText());
                Integer xSheet=Integer.parseInt(xsheet.getText());
                Integer xendSheet=Integer.parseInt(endSheet.getText());
                
                Messages.show("StartLine1="+xstartLine);
                Calendar calendar = Calendar.getInstance();
                java.util.Date now = calendar.getTime();
                pr.timestamp = new java.sql.Timestamp(now.getTime());
                pr.setStartLine(xstartLine);
                pr.setEndLine(xendLine);
                pr.setSheet(xSheet);
                pr.setEndSheet(xendSheet);
                pr.ParseExcelPrice(progress, "1");
                
                //pr.deleteOldProducts("1");

                txLoadPrice1.setBackground(Color.GREEN);
                Messages.show("Загрузка прайса завершена");
                return null;  // return your result
            }
        };
    }

    private boolean testCurs(JTextField t) {
        Boolean res = true;
        try {
            Double.parseDouble(t.getText());
            t.setBackground(Color.white);
        } catch (Exception e) {
            t.requestFocus();
            t.setBackground(Color.red);
            res = false;
            JOptionPane.showMessageDialog(null, "Неправильно введена начальная строка", "Неправильно введена начальная строка", JOptionPane.INFORMATION_MESSAGE);
        }
        return res;
    }

    private boolean testStartLine(JTextField t) {
        Boolean res = true;
        try {
            Integer i = Integer.parseInt(t.getText());
            if (i > 0) {
                t.setBackground(Color.white);
            } else {
                t.requestFocus();
                t.setBackground(Color.red);
                res = false;
                JOptionPane.showMessageDialog(null, "Неправильно введен курс", "Неправильно введен курс", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
        }
        return res;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelPrices;
    private javax.swing.JButton btLoadPrice1;
    private javax.swing.JTextField endLine;
    private javax.swing.JTextField endSheet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbLoadPrice1;
    private javax.swing.JLabel lbProgress;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField startLine;
    private javax.swing.JTextArea taReport;
    private javax.swing.JLabel ttData;
    private javax.swing.JLabel ttData1;
    private javax.swing.JLabel ttData2;
    private javax.swing.JLabel ttData3;
    private javax.swing.JLabel ttData4;
    private javax.swing.JLabel ttData5;
    private javax.swing.JLabel ttData6;
    private javax.swing.JTextField txCurs1;
    private javax.swing.JTextField txLoadPrice1;
    private javax.swing.JTextField xsheet;
    // End of variables declaration//GEN-END:variables
}
